services:
  # Combined API and WebAssembly service
  tsp-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_HTTPS_PORT=
      - ASPNETCORE_HTTPS_PORTS=
      - ASPNETCORE_HTTP_PORT=5001
      - DOTNET_RUNNING_IN_CONTAINER=true
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alternative: Separate API and WebAssembly services
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: api
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5001
  #   volumes:
  #     - ./logs:/app/logs
  #   restart: unless-stopped

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: wasm
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #   restart: unless-stopped

networks:
  default:
    name: tsp-lab-network

volumes:
  logs:
    driver: local
